name: zenstack-cache

volumes:
  postgres-data:
  redis-data:
  redis-insight:

networks:
  workspace:
    external: false

services:
  redis:
    container_name: zenstack-cache-redis
    image: redis:3.0
    command: redis-server
    networks:
      - workspace
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  workspace:
    container_name: zenstack-cache-workspace
    image: mcr.microsoft.com/devcontainers/javascript-node:20
    volumes:
      - ..:/workspace:cached
    env_file: ./.env
    command: sleep infinity
    networks:
      - workspace

  redis-insight:
    container_name: zenstack-cache-redis-insight
    image: redis/redisinsight:3.0
    depends_on:
      - redis
    networks:
      - workspace
    ports:
      - 5540:5540
    volumes:
      - redis-insight:/data